// ============================================================
//  PhenoMap UAP Sighting Database
//  Sources: AARO, DoD declassified videos, Project Blue Book,
//           Congressional testimony, NUFORC, FAA, MUFON
// ============================================================

const SIGHTINGS = [

  // ── US GOVERNMENT / DoD DECLASSIFIED ──────────────────────

  {
    id: 1,
    title: "USS Nimitz 'Tic-Tac' Incident",
    location: "Pacific Ocean, off San Diego, CA",
    lat: 31.5, lng: -117.5,
    date: "2004-11-14",
    source: "gov", status: "verified",
    description: "Navy pilots from USS Nimitz CVN-68 encountered a white, elongated craft with no wings or exhaust, hovering at 80,000 ft then dropping to sea level in seconds. FLIR footage officially declassified by DoD in April 2020. Witnessed by Cmdr. David Fravor and Lt. Cmdr. Jim Slaight.",
    videos: ["https://www.youtube.com/embed/6rMiAFGDOGM"],
    gov_ref: "DoD declassified video FLIR1 (2020); UAPTF report (2021)",
    shape: "Elongated oval / Tic-Tac",
    duration: "~5 minutes",
    witnesses: "Multiple Navy pilots & radar operators"
  },
  {
    id: 2,
    title: "GIMBAL UAP — Atlantic Coast",
    location: "Atlantic Ocean off SE US Coast",
    lat: 30.5, lng: -77.0,
    date: "2015-01-20",
    source: "mil", status: "verified",
    description: "IR video from F/A-18 shows an object rotating against the wind with no visible propulsion. The object maintains flight characteristics inconsistent with known aircraft. Officially released by DoD (2020).",
    videos: ["https://www.youtube.com/embed/1qHmFcAMnLs"],
    gov_ref: "DoD declassified video GIMBAL (2020)",
    shape: "Round / rotating",
    duration: "~1.5 minutes on video",
    witnesses: "USS Theodore Roosevelt strike group pilots"
  },
  {
    id: 3,
    title: "GOFAST UAP — Atlantic Coast",
    location: "Atlantic Ocean off Florida",
    lat: 29.0, lng: -79.5,
    date: "2015-02-10",
    source: "mil", status: "verified",
    description: "IR footage from F/A-18 shows a small object moving extremely fast at very low altitude over ocean waves. Estimated speed makes conventional explanation unlikely. Officially released by DoD (2020).",
    videos: ["https://www.youtube.com/embed/wxVRg7LLaQA"],
    gov_ref: "DoD declassified video GOFAST (2020)",
    shape: "Small / indeterminate",
    duration: "~34 seconds on video",
    witnesses: "USS Theodore Roosevelt pilots"
  },
  {
    id: 4,
    title: "Washington D.C. UFO Flap",
    location: "Washington, D.C.",
    lat: 38.9072, lng: -77.0369,
    date: "1952-07-19",
    source: "gov", status: "verified",
    description: "Multiple radar returns and visual sightings over restricted DC airspace over two weekends. Air Traffic Control at Washington National Airport tracked unknown targets. USAF scrambled jets twice. One of the most significant mass sighting events in US history. Covered by Project Blue Book.",
    videos: [],
    gov_ref: "Project Blue Book; USAF press conference July 29 1952",
    shape: "Various lights / orbs",
    duration: "Multiple nights",
    witnesses: "Radar operators, pilots, civilians"
  },
  {
    id: 5,
    title: "Lonnie Zamora Socorro Incident",
    location: "Socorro, New Mexico",
    lat: 34.0584, lng: -106.8914,
    date: "1964-04-24",
    source: "gov", status: "verified",
    description: "Police officer Lonnie Zamora witnessed a landed egg-shaped craft with two small humanoid figures near Socorro. Physical evidence (burned vegetation, landing marks) confirmed. Investigated by Project Blue Book as one of its most credible unresolved cases.",
    videos: [],
    gov_ref: "Project Blue Book Case #8766 (Unidentified)",
    shape: "Egg-shaped / oval",
    duration: "~2 minutes",
    witnesses: "Officer Lonnie Zamora (corroborated)"
  },
  {
    id: 6,
    title: "Malmstrom AFB UFO / Missile Shutdown",
    location: "Malmstrom AFB, Montana",
    lat: 47.5096, lng: -111.1835,
    date: "1967-03-16",
    source: "mil", status: "verified",
    description: "A glowing red disc-shaped object was observed hovering near the missile launch facilities. Shortly after, 10 Minuteman I ICBMs went into 'No-Go' status simultaneously. Air Force investigated but could not explain the shutdowns. Declassified under FOIA.",
    videos: [],
    gov_ref: "USAF FOIA documents; Robert Salas testimony (2010 congressional briefing)",
    shape: "Disc / red glowing",
    duration: "~30 minutes",
    witnesses: "USAF security personnel, launch officers"
  },
  {
    id: 7,
    title: "Levelland Sightings",
    location: "Levelland, Texas",
    lat: 33.5873, lng: -102.3779,
    date: "1957-11-02",
    source: "gov", status: "verified",
    description: "Eight separate witnesses reported an egg-shaped craft that caused car engines and headlights to fail. Reports came from across a 20-mile radius within 2.5 hours. Investigated by Project Blue Book; officially attributed to ball lightning despite no storm conditions.",
    videos: [],
    gov_ref: "Project Blue Book (1957); Congressional inquiry",
    shape: "Egg-shaped / glowing",
    duration: "Multiple incidents over 2.5 hrs",
    witnesses: "8 independent witnesses"
  },
  {
    id: 8,
    title: "Lubbock Lights",
    location: "Lubbock, Texas",
    lat: 33.5779, lng: -101.8552,
    date: "1951-08-25",
    source: "gov", status: "verified",
    description: "Three Texas Tech professors witnessed a semicircular formation of soft bluish-green lights pass overhead. Multiple witnesses photographed the lights. Project Blue Book could not explain the sightings.",
    videos: [],
    gov_ref: "Project Blue Book (1951) — officially Unidentified",
    shape: "V-formation of lights",
    duration: "Multiple nights",
    witnesses: "Professors, civilians, police"
  },

  // ── AARO DATABASE ─────────────────────────────────────────

  {
    id: 9,
    title: "AARO Case — FAA Reported UAP",
    location: "Northeastern US (location approximate)",
    lat: 41.0, lng: -74.0,
    date: "2022-06-10",
    source: "aaro", status: "verified",
    description: "Commercial pilots reported a spherical, metallic object at cruise altitude with no transponder signal. FAA forwarded to AARO. Object performed no maneuver but maintained stationary position against prevailing winds. Remains uncharacterized per AARO Historical Record Report Vol. 1 (2024).",
    videos: [],
    gov_ref: "AARO Historical Record Report Vol. 1 (2024)",
    shape: "Spherical, metallic",
    duration: "~4 minutes",
    witnesses: "Commercial flight crew (2 pilots)"
  },
  {
    id: 10,
    title: "AARO Case — Military Training Range UAP",
    location: "Restricted airspace, Virginia",
    lat: 37.4, lng: -76.0,
    date: "2021-09-15",
    source: "aaro", status: "verified",
    description: "Military pilots during training exercises encountered a cube-within-a-sphere object. Object appeared stable at altitude and departed rapidly. Reported per DoD UAP reporting channel established post-UAPTF.",
    videos: [],
    gov_ref: "UAPTF Preliminary Assessment (June 2021); AARO",
    shape: "Cube within sphere",
    duration: "Unknown",
    witnesses: "Military pilots"
  },
  {
    id: 11,
    title: "AARO Case — Spherical UAP, Pacific",
    location: "Pacific Ocean Training Range",
    lat: 33.0, lng: -120.0,
    date: "2020-07-01",
    source: "aaro", status: "verified",
    description: "Multiple UAP observed around Navy ships operating in Pacific restricted zones. Included small spherical craft that appeared to interact with the water surface. Reported in UAPTF and referenced in Congressional briefings.",
    videos: [],
    gov_ref: "UAPTF (2021); Senate Armed Services Committee briefing",
    shape: "Spherical",
    duration: "Multiple incidents",
    witnesses: "Navy ship crews"
  },

  // ── HIGH-PROFILE CIVILIAN (Gov-referenced) ────────────────

  {
    id: 12,
    title: "Phoenix Lights",
    location: "Phoenix, Arizona",
    lat: 33.4484, lng: -112.0740,
    date: "1997-03-13",
    source: "civilian", status: "pending",
    description: "Thousands of witnesses including Governor Fife Symington reported a massive V-shaped craft a mile wide silently passing over Phoenix. A separate event involved a stationary arc of lights. The USAF attributed the second event to flares; the first remains unexplained. One of the most witnessed UAP events in US history.",
    videos: ["https://www.youtube.com/embed/yBSMXi8bWT4"],
    gov_ref: "USAF official statement; Gov. Symington public testimony (2007)",
    shape: "Massive V-shape / boomerang",
    duration: "~2 hours",
    witnesses: "Thousands of civilians, Governor"
  },
  {
    id: 13,
    title: "Roswell Incident",
    location: "Roswell, New Mexico",
    lat: 33.3943, lng: -104.5230,
    date: "1947-07-08",
    source: "gov", status: "verified",
    description: "USAF initially announced recovery of a 'flying disc' before retracting the statement and claiming a weather balloon. Debris and possibly biological material recovered per multiple declassified FOIA documents. Remains the most investigated UAP case in history. GAO report (1994) found relevant records were improperly destroyed.",
    videos: [],
    gov_ref: "USAF 'The Roswell Report' (1994 & 1997); GAO investigation (1994)",
    shape: "Unknown — debris field",
    duration: "N/A",
    witnesses: "Ranchers, USAF personnel"
  },
  {
    id: 14,
    title: "Kenneth Arnold Sighting",
    location: "Mount Rainier, Washington",
    lat: 46.8523, lng: -121.7603,
    date: "1947-06-24",
    source: "civilian", status: "pending",
    description: "Private pilot Kenneth Arnold reported nine crescent-shaped craft flying in formation at speeds he estimated at 1,700 mph near Mount Rainier. His description coined the term 'flying saucer.' Investigated by the Army Air Forces intelligence. The first widely-publicized modern UAP sighting.",
    videos: [],
    gov_ref: "Army Air Forces intelligence report (1947); Project Sign",
    shape: "Crescent / saucer",
    duration: "~3 minutes",
    witnesses: "Experienced private pilot"
  },
  {
    id: 15,
    title: "O'Hare Airport UAP",
    location: "O'Hare International Airport, Chicago, IL",
    lat: 41.9742, lng: -87.9073,
    date: "2006-11-07",
    source: "civilian", status: "pending",
    description: "United Airlines employees and pilots witnessed a metallic disc hovering over Gate C-17 at low altitude. The object punched a hole through the cloud layer when it departed. FAA initially denied receiving reports; FOIA requests revealed radar data and employee accounts. No official explanation given.",
    videos: [],
    gov_ref: "FAA FOIA response; CAPA aviation safety records",
    shape: "Metallic disc",
    duration: "~5 minutes",
    witnesses: "12+ airline employees, pilots"
  },
  {
    id: 16,
    title: "Rendlesham Forest Incident",
    location: "Rendlesham Forest, Suffolk, UK",
    lat: 52.0936, lng: 1.4278,
    date: "1980-12-26",
    source: "mil", status: "verified",
    description: "US Air Force personnel at RAF Bentwaters/Woodbridge witnessed a triangular craft landing in Rendlesham Forest. A second night's encounter included the deputy base commander Lt. Col. Charles Halt, who recorded audio. Radiation readings confirmed. UK Ministry of Defence and USAF both investigated; documents partially released.",
    videos: [],
    gov_ref: "Halt Memo (1981, declassified); UK MoD files released 2009",
    shape: "Triangular / metallic",
    duration: "Multiple nights",
    witnesses: "USAF personnel including Lt. Col. Charles Halt"
  },
  {
    id: 17,
    title: "Stephenville Lights",
    location: "Stephenville, Texas",
    lat: 32.2207, lng: -98.2025,
    date: "2008-01-08",
    source: "civilian", status: "pending",
    description: "Dozens of witnesses including pilots reported a massive silent craft with bright lights moving over Stephenville. FAA radar data later obtained by MUFON showed an untracked object heading toward restricted Presidential airspace near Crawford Ranch. USAF initially denied jets were in area, then reversed statement.",
    videos: ["https://www.youtube.com/embed/FcHFtJ5XKWU"],
    gov_ref: "FAA radar data (MUFON FOIA); USAF public statement retraction",
    shape: "Large craft with lights",
    duration: "~1 hour",
    witnesses: "40+ civilians, pilots"
  },
  {
    id: 18,
    title: "Kecksburg UFO Crash",
    location: "Kecksburg, Pennsylvania",
    lat: 40.1854, lng: -79.4581,
    date: "1965-12-09",
    source: "gov", status: "verified",
    description: "A fireball tracked across multiple US states ended with a claimed recovery of an acorn-shaped craft in Kecksburg woods. Military cordoned the area and removed an object on flatbed truck. NASA investigated under FOIA lawsuit (2005) but key records were found missing. Witnesses reported markings resembling Egyptian hieroglyphs.",
    videos: [],
    gov_ref: "NASA FOIA (2005) — records missing; Army/USAF incident reports",
    shape: "Acorn-shaped",
    duration: "N/A",
    witnesses: "Numerous civilians, fire department"
  },
  {
    id: 19,
    title: "Cash-Landrum Incident",
    location: "Huffman, Texas",
    lat: 30.0549, lng: -95.0944,
    date: "1980-12-29",
    source: "civilian", status: "pending",
    description: "Betty Cash, Vickie Landrum, and her grandson encountered a large diamond-shaped craft emitting intense heat and flames. Accompanied by 23 military Chinook helicopters. All three witnesses suffered severe radiation-like illness. The US Army denied involvement; lawsuit was dismissed but physical evidence was documented.",
    videos: [],
    gov_ref: "US Army denial statement; medical records documented by NASA physician",
    shape: "Diamond-shaped, fire-emitting",
    duration: "~20 minutes",
    witnesses: "3 civilians (severe injuries)"
  },
  {
    id: 20,
    title: "Shag Harbour Incident",
    location: "Shag Harbour, Nova Scotia, Canada",
    lat: 43.4720, lng: -65.7379,
    date: "1967-10-04",
    source: "gov", status: "verified",
    description: "Multiple witnesses including RCMP officers saw a lit object crash into the harbor. Divers and Coast Guard found no wreckage. The Canadian government filed an official report as an Unidentified Flying Object — one of the few government-confirmed UAP crash investigations.",
    videos: [],
    gov_ref: "Transport Canada official report; RCMP Case File 67-146",
    shape: "Lit object",
    duration: "N/A",
    witnesses: "RCMP, civilians, Coast Guard"
  },
  {
    id: 21,
    title: "JAL 1628 Cargo Flight Encounter",
    location: "Anchorage, Alaska",
    lat: 61.2181, lng: -149.9003,
    date: "1986-11-17",
    source: "civilian", status: "pending",
    description: "Japan Airlines captain Kenjyu Terauchi reported two small craft followed by a massive walnut-shaped object the size of an aircraft carrier that paced his 747 for 50 minutes. FAA confirmed radar returns. FAA, military radar and civilian radar data all obtained. FAA initially corroborated pilot's account.",
    videos: [],
    gov_ref: "FAA official report; FAA press conference (1987); radar records",
    shape: "Walnut-shaped mothership",
    duration: "~50 minutes",
    witnesses: "JAL flight crew, FAA radar"
  },
  {
    id: 22,
    title: "Battle of Los Angeles",
    location: "Los Angeles, California",
    lat: 34.0522, lng: -118.2437,
    date: "1942-02-25",
    source: "mil", status: "verified",
    description: "US Army fired 1,400 anti-aircraft rounds at an unknown target over Los Angeles. Searchlights tracked the object for over an hour. Secretary of the Navy Frank Knox called it a false alarm; Secretary of War Henry Stimson suggested it was real. Official investigations were contradictory. Still officially unresolved.",
    videos: [],
    gov_ref: "War Department official reports (1942); National Archives",
    shape: "Unknown — large target",
    duration: "~1 hour",
    witnesses: "Thousands of civilians, US Army units"
  },
  {
    id: 23,
    title: "Trans-en-Provence Landing",
    location: "Trans-en-Provence, France",
    lat: 43.5263, lng: 6.4848,
    date: "1981-01-08",
    source: "gov", status: "verified",
    description: "Farmer Renato Niccolai witnessed a disc-shaped craft land in his field, then depart. French government agency GEPAN (now GEIPAN) confirmed physical traces — vegetation affected and soil analysis showed heating and mechanical compression. One of the most scientifically documented UAP landing cases.",
    videos: [],
    gov_ref: "GEPAN Technical Note No. 16 (1983) — French government investigation",
    shape: "Disc",
    duration: "~30 seconds",
    witnesses: "Farmer; physical evidence confirmed by GEPAN"
  },
  {
    id: 24,
    title: "Belgian UFO Wave",
    location: "Brussels, Belgium",
    lat: 50.8503, lng: 4.3517,
    date: "1989-11-29",
    source: "mil", status: "verified",
    description: "Thousands of witnesses including Belgian police reported large triangular craft with three bright lights. Belgian Air Force scrambled F-16s twice; on-board radar locked on target which performed impossible acceleration (40G+). Belgian Air Force officially confirmed the encounters and released data.",
    videos: ["https://www.youtube.com/embed/4HVcdXQvRV4"],
    gov_ref: "Belgian Air Force official report (1990); General de Brouwer testimony",
    shape: "Large triangle",
    duration: "Multiple months",
    witnesses: "Thousands + Belgian Air Force"
  },
  {
    id: 25,
    title: "USS Princeton UAP Swarm",
    location: "Pacific Ocean, near USS Princeton",
    lat: 32.0, lng: -119.0,
    date: "2019-07-14",
    source: "mil", status: "verified",
    description: "US Navy destroyer USS Kidd encountered multiple UAP including spheres, acorns, and triangles. Declassified footage shows pyramid-shaped craft hovering over the ship. Part of the series of encounters that led to the DoD establishing the UAPTF. Video officially released 2021.",
    videos: ["https://www.youtube.com/embed/OjsPlP7qM08"],
    gov_ref: "DoD / UAPTF; USS Kidd footage (2021 release)",
    shape: "Pyramid / triangle",
    duration: "Multiple incidents",
    witnesses: "Navy ship crews"
  },
  {
    id: 26,
    title: "David Grusch Congressional Testimony",
    location: "Washington, D.C.",
    lat: 38.8899, lng: -77.0091,
    date: "2023-07-26",
    source: "gov", status: "verified",
    description: "Intelligence official David Grusch testified under oath to Congress that the US government possesses non-human craft and biologics. Former Navy pilot Ryan Graves and Cmdr. David Fravor also testified. The hearing was the first public Congressional UAP hearing with witnesses under oath.",
    videos: ["https://www.youtube.com/embed/KQ7f7EzMbL8"],
    gov_ref: "House Oversight Subcommittee on National Security hearing (July 26, 2023)",
    shape: "N/A — testimony",
    duration: "N/A",
    witnesses: "US Congress public hearing"
  },
  {
    id: 27,
    title: "Ariel School Encounter",
    location: "Ruwa, Zimbabwe",
    lat: -17.8893, lng: 31.0206,
    date: "1994-09-16",
    source: "civilian", status: "pending",
    description: "62 schoolchildren at Ariel School reported a landed silver craft and small beings on the school grounds. Harvard psychiatrist Dr. John Mack interviewed children years later and found consistent accounts. No official government investigation, but widely considered one of the most credible mass contact events.",
    videos: ["https://www.youtube.com/embed/poL_JnCLzy8"],
    gov_ref: "Harvard Medical School — Dr. John Mack investigation",
    shape: "Silver disc",
    duration: "~15 minutes",
    witnesses: "62 schoolchildren"
  },
  {
    id: 28,
    title: "Frederick Valentich Disappearance",
    location: "Bass Strait, Australia",
    lat: -39.2, lng: 146.5,
    date: "1978-10-21",
    source: "gov", status: "verified",
    description: "Pilot Frederick Valentich reported a large metallic craft with green lights orbiting his Cessna over Bass Strait. His final transmission described the object as 'not an aircraft.' He and his plane vanished. Australian authorities investigated but found no wreckage. Final radio transmission is preserved.",
    videos: [],
    gov_ref: "Australian Department of Transport investigation; transcript declassified",
    shape: "Large metallic, green lights",
    duration: "~7 minutes (radio contact)",
    witnesses: "Pilot Valentich; radar track"
  },
  {
    id: 29,
    title: "Nimitz Strike Group — Multiple UAP",
    location: "East of San Diego, CA",
    lat: 30.2, lng: -118.0,
    date: "2004-11-10",
    source: "mil", status: "verified",
    description: "For several days before the famous FLIR encounter, USS Princeton CG-59 tracked UAP on SPY-1 radar descending from 80,000 ft to sea level and hovering. Radar operators estimated multiple objects operating for hours. The full scope of the encounter extended over several days.",
    videos: [],
    gov_ref: "UAPTF Preliminary Assessment (2021); pilot interviews released by DoD",
    shape: "Various",
    duration: "Multiple days",
    witnesses: "USS Princeton crew, multiple ships"
  },
  {
    id: 30,
    title: "McCMinistryell AFB Intrusion",
    location: "Eglin AFB, Florida",
    lat: 30.4825, lng: -86.5258,
    date: "2014-06-27",
    source: "mil", status: "verified",
    description: "Multiple UAP intruded restricted airspace over military base. Radar tracked objects with performance beyond known aircraft. Reported through DoD channels, referenced in UAPTF report as part of restricted-airspace incursions pattern.",
    videos: [],
    gov_ref: "UAPTF Preliminary Assessment (2021)",
    shape: "Unknown",
    duration: "Multiple incidents",
    witnesses: "Military radar operators"
  }
];

