// ============================================================
//  HiggsField Hub — AI Video Creation Database
//  Sources: WAN 2.5, Cinema Studio 2.5, Kling 3.0, Community
// ============================================================

const CREATIONS = [

  // ── WAN 2.5 SHOWCASE ─────────────────────────────────────

  {
    id: 1,
    title: "Desert Chase — Native Dialogue Scene",
    location: "Los Angeles, CA, USA",
    lat: 34.0522, lng: -118.2437,
    date: "2026-03-15",
    source: "wan", status: "featured",
    description: "A 10-second cinematic chase scene generated entirely with WAN 2.5 text-to-video. Features native dialogue between two characters, ambient desert wind sounds, and a dramatic orchestral score — all generated in a single pass. 1080p at 24fps.",
    videos: ["https://www.youtube.com/embed/dQw4w9WgXcQ"],
    ref: "Higgsfield WAN 2.5 launch showcase",
    style: "Cinematic / Film",
    duration: "10 seconds",
    creator: "Higgsfield Team"
  },
  {
    id: 2,
    title: "Tokyo Neon — Cyberpunk Street Walk",
    location: "Tokyo, Japan",
    lat: 35.6762, lng: 139.6503,
    date: "2026-03-18",
    source: "wan", status: "featured",
    description: "First-person walking POV through a rain-soaked neon-lit Tokyo alley. WAN 2.5 generated realistic rain sounds, distant city ambience, and footstep audio natively. Prompt: 'POV walking through cyberpunk Tokyo alley at night, neon reflections on wet ground, cinematic.'",
    videos: [],
    ref: "Community showcase — top rated",
    style: "Cinematic / Film",
    duration: "10 seconds",
    creator: "NeonDreamer_AI"
  },
  {
    id: 3,
    title: "Coffee Brand — Product Commercial",
    location: "New York, NY, USA",
    lat: 40.7128, lng: -74.0060,
    date: "2026-03-20",
    source: "wan", status: "featured",
    description: "A polished 10-second coffee brand ad generated with WAN 2.5. Shows steam rising from a ceramic cup, close-up pour, and a lifestyle shot of someone sipping by a window. Voiceover narration generated natively.",
    videos: [],
    ref: "Marketing use case demo",
    style: "Commercial / Ad",
    duration: "10 seconds",
    creator: "AdForge Studio"
  },
  {
    id: 4,
    title: "Underwater Coral Reef Documentary",
    location: "Sydney, Australia",
    lat: -33.8688, lng: 151.2093,
    date: "2026-03-22",
    source: "wan", status: "featured",
    description: "Stunning underwater footage of a coral reef with tropical fish. WAN 2.5 generated ambient ocean sounds and bubbles. Used for a climate awareness short film. Resolution: 1080p, Duration: 10s.",
    videos: [],
    ref: "Environmental awareness project",
    style: "Documentary",
    duration: "10 seconds",
    creator: "OceanLens Creative"
  },

  // ── CINEMA STUDIO 2.5 ────────────────────────────────────

  {
    id: 5,
    title: "Soul Cast Short — The Detective",
    location: "London, UK",
    lat: 51.5074, lng: -0.1278,
    date: "2026-02-28",
    source: "cinema", status: "featured",
    description: "A noir-style detective scene created with Cinema Studio 2.5 using 3 Soul Cast AI actors. Character consistency maintained across 5 shots. In-studio color grading applied with a cold blue/amber palette. Each actor was generated and saved to the Soul Cast library.",
    videos: [],
    ref: "Cinema Studio 2.5 feature demo",
    style: "Cinematic / Film",
    duration: "30 seconds (5 shots)",
    creator: "FilmForge AI"
  },
  {
    id: 6,
    title: "Fashion Campaign — Spring Collection",
    location: "Paris, France",
    lat: 48.8566, lng: 2.3522,
    date: "2026-03-05",
    source: "cinema", status: "featured",
    description: "A fashion campaign video featuring AI-generated models walking a virtual runway. Cinema Studio 2.5's Soul Cast feature ensured consistent model appearance across 8 different outfit changes. Color graded with warm golden tones.",
    videos: [],
    ref: "Fashion industry use case",
    style: "Commercial / Ad",
    duration: "45 seconds (8 shots)",
    creator: "Vogue Digital Labs"
  },
  {
    id: 7,
    title: "Animated Explainer — How AI Works",
    location: "San Francisco, CA, USA",
    lat: 37.7749, lng: -122.4194,
    date: "2026-03-10",
    source: "cinema", status: "featured",
    description: "An educational explainer video about how neural networks process information. Created entirely in Cinema Studio 2.5 using the animation preset. Features smooth transitions, text overlays added in post, and a narrator voice from WAN 2.5.",
    videos: [],
    ref: "Education content showcase",
    style: "Animation",
    duration: "60 seconds",
    creator: "LearnAI Channel"
  },
  {
    id: 8,
    title: "Music Video — Synthwave Dreams",
    location: "Berlin, Germany",
    lat: 52.5200, lng: 13.4050,
    date: "2026-03-12",
    source: "cinema", status: "featured",
    description: "A retro-futuristic synthwave music video created with Cinema Studio 2.5. Features a consistent AI actor driving through a neon cityscape. Soul Cast maintained character identity across 12 cuts. Color graded with heavy purple/cyan split toning.",
    videos: [],
    ref: "Music video production demo",
    style: "Music Video",
    duration: "3 minutes (12 shots)",
    creator: "RetroWave Productions"
  },

  // ── KLING 3.0 ────────────────────────────────────────────

  {
    id: 9,
    title: "Drone Fly-Through — Ancient Temple",
    location: "Siem Reap, Cambodia",
    lat: 13.4125, lng: 103.8670,
    date: "2026-03-01",
    source: "kling", status: "featured",
    description: "A breathtaking drone-style fly-through of an ancient temple generated with Kling 3.0. Cinematic camera presets used for smooth orbiting and reveal shots. Photorealistic stone textures and volumetric light rays through the canopy.",
    videos: [],
    ref: "Kling 3.0 cinematic preset showcase",
    style: "Cinematic / Film",
    duration: "15 seconds",
    creator: "AerialVision AI"
  },
  {
    id: 10,
    title: "Product Unboxing — Tech Gadget",
    location: "Shenzhen, China",
    lat: 22.5431, lng: 114.0579,
    date: "2026-03-08",
    source: "kling", status: "featured",
    description: "A sleek product unboxing video for a fictional tech gadget. Kling 3.0's advanced motion control created smooth hands opening a box with precise finger movements. Studio lighting with soft shadows.",
    videos: [],
    ref: "E-commerce video demo",
    style: "Commercial / Ad",
    duration: "12 seconds",
    creator: "TechReview AI"
  },
  {
    id: 11,
    title: "Food Prep — Sushi Making",
    location: "Osaka, Japan",
    lat: 34.6937, lng: 135.5023,
    date: "2026-03-14",
    source: "kling", status: "featured",
    description: "Close-up food preparation video showing sushi being assembled by a chef. Kling 3.0 handled the fine motor details of knife work and rice placement. Warm overhead lighting with shallow depth of field.",
    videos: [],
    ref: "Food content creation demo",
    style: "Social Media / Short",
    duration: "8 seconds",
    creator: "FoodieAI"
  },

  // ── COMMUNITY CREATIONS ──────────────────────────────────

  {
    id: 12,
    title: "TikTok Transition — Outfit Change",
    location: "Miami, FL, USA",
    lat: 25.7617, lng: -80.1918,
    date: "2026-03-25",
    source: "community", status: "pending",
    description: "A viral-style TikTok transition video where an AI character snaps their fingers and changes outfits. Created with WAN 2.5 free tier. Gained 2M views when posted as a demo of AI capabilities.",
    videos: [],
    ref: "User submission — viral content",
    style: "Social Media / Short",
    duration: "5 seconds",
    creator: "ViralVince"
  },
  {
    id: 13,
    title: "Abstract Art — Liquid Metal Morphing",
    location: "Stockholm, Sweden",
    lat: 59.3293, lng: 18.0686,
    date: "2026-03-26",
    source: "community", status: "pending",
    description: "An experimental art piece showing liquid mercury-like metal morphing into geometric shapes. Created using WAN 2.5 with heavy negative prompting to achieve the abstract look. No audio — intended as a gallery installation loop.",
    videos: [],
    ref: "Art installation project",
    style: "Experimental / Art",
    duration: "10 seconds",
    creator: "DigitalSculptor"
  },
  {
    id: 14,
    title: "Pet Portrait — Golden Retriever in Meadow",
    location: "Denver, CO, USA",
    lat: 39.7392, lng: -104.9903,
    date: "2026-03-27",
    source: "community", status: "pending",
    description: "A heartwarming video of a golden retriever running through a sunlit meadow with butterflies. Generated with Kling 3.0 free tier. The natural movement and fur physics impressed the community.",
    videos: [],
    ref: "Community favorite",
    style: "Social Media / Short",
    duration: "8 seconds",
    creator: "PetLover_AI"
  },
  {
    id: 15,
    title: "Architectural Visualization — Modern Villa",
    location: "Dubai, UAE",
    lat: 25.2048, lng: 55.2708,
    date: "2026-03-20",
    source: "community", status: "featured",
    description: "A photorealistic fly-through of a modern villa design. Created with Cinema Studio 2.5 for an architecture firm's client presentation. Features interior and exterior shots with consistent lighting across all angles.",
    videos: [],
    ref: "Architecture industry use case",
    style: "Commercial / Ad",
    duration: "20 seconds",
    creator: "ArchViz Pro"
  },
  {
    id: 16,
    title: "Sci-Fi Short — First Contact",
    location: "Cape Town, South Africa",
    lat: -33.9249, lng: 18.4241,
    date: "2026-03-15",
    source: "cinema", status: "featured",
    description: "A 2-minute sci-fi short film about humanity's first alien encounter. Created entirely with Cinema Studio 2.5 using 3 Soul Cast characters. Features space VFX, dialogue, and an original score generated with WAN 2.5 audio.",
    videos: [],
    ref: "Sci-fi short film competition entry",
    style: "Cinematic / Film",
    duration: "2 minutes",
    creator: "CosmicNarrative"
  },
  {
    id: 17,
    title: "Yoga Tutorial — Morning Flow",
    location: "Bali, Indonesia",
    lat: -8.3405, lng: 115.0920,
    date: "2026-03-18",
    source: "wan", status: "pending",
    description: "An AI-generated yoga tutorial video with a virtual instructor demonstrating a morning flow routine. WAN 2.5 generated calming ambient music and the instructor's voice narration guiding poses.",
    videos: [],
    ref: "Wellness content creation",
    style: "Social Media / Short",
    duration: "10 seconds",
    creator: "ZenFlow Digital"
  },
  {
    id: 18,
    title: "Car Commercial — Electric SUV",
    location: "Munich, Germany",
    lat: 48.1351, lng: 11.5820,
    date: "2026-03-22",
    source: "kling", status: "featured",
    description: "A high-end car commercial for a fictional electric SUV driving through the Alps. Kling 3.0's cinematic camera presets created sweeping aerial and tracking shots. Photorealistic reflections on the car body.",
    videos: [],
    ref: "Automotive marketing demo",
    style: "Commercial / Ad",
    duration: "15 seconds",
    creator: "AutoVision AI"
  },
  {
    id: 19,
    title: "Wedding Highlight Reel — AI Generated",
    location: "Santorini, Greece",
    lat: 36.3932, lng: 25.4615,
    date: "2026-03-28",
    source: "cinema", status: "pending",
    description: "A concept wedding highlight reel generated with Cinema Studio 2.5. Soul Cast was used to maintain consistent bride/groom appearance across 10 shots in different Santorini locations. Warm, romantic color grading.",
    videos: [],
    ref: "Event videography concept",
    style: "Cinematic / Film",
    duration: "45 seconds",
    creator: "WeddingAI Studio"
  },
  {
    id: 20,
    title: "Game Trailer — Fantasy RPG",
    location: "Seoul, South Korea",
    lat: 37.5665, lng: 126.9780,
    date: "2026-03-30",
    source: "wan", status: "featured",
    description: "A game trailer for a fictional fantasy RPG featuring epic battle scenes and a narrator voiceover. Generated with WAN 2.5's native audio. Includes sword clash sound effects and an orchestral battle theme.",
    videos: [],
    ref: "Gaming industry demo",
    style: "Cinematic / Film",
    duration: "10 seconds",
    creator: "GameForge Studios"
  },
  {
    id: 21,
    title: "Real Estate Virtual Tour",
    location: "Austin, TX, USA",
    lat: 30.2672, lng: -97.7431,
    date: "2026-03-19",
    source: "kling", status: "featured",
    description: "A virtual property tour for a luxury home listing. Kling 3.0 generated smooth room-to-room transitions with consistent lighting. Used by a real estate agent for a remote buyer presentation.",
    videos: [],
    ref: "Real estate industry adoption",
    style: "Commercial / Ad",
    duration: "20 seconds",
    creator: "HomeView AI"
  },
  {
    id: 22,
    title: "Nature Timelapse — Northern Lights",
    location: "Reykjavik, Iceland",
    lat: 64.1466, lng: -21.9426,
    date: "2026-03-16",
    source: "wan", status: "featured",
    description: "A breathtaking AI-generated timelapse of the Aurora Borealis over an Icelandic landscape. WAN 2.5 generated subtle wind ambience and a distant wolf howl. Photorealistic star field and aurora movement.",
    videos: [],
    ref: "Nature content showcase",
    style: "Cinematic / Film",
    duration: "10 seconds",
    creator: "ArcticLens"
  },
  {
    id: 23,
    title: "Instagram Reel — Street Food Tour",
    location: "Bangkok, Thailand",
    lat: 13.7563, lng: 100.5018,
    date: "2026-03-24",
    source: "community", status: "pending",
    description: "A fast-paced Instagram reel showing various Bangkok street food stalls. Quick cuts with sizzling sound effects. Created with WAN 2.5 free tier as a travel content concept.",
    videos: [],
    ref: "Travel content creation",
    style: "Social Media / Short",
    duration: "10 seconds",
    creator: "TravelBites"
  },
  {
    id: 24,
    title: "Corporate Training — Safety Procedures",
    location: "Chicago, IL, USA",
    lat: 41.8781, lng: -87.6298,
    date: "2026-03-21",
    source: "cinema", status: "featured",
    description: "A workplace safety training video featuring AI actors demonstrating proper procedures. Cinema Studio 2.5 Soul Cast ensured the same employees appeared consistently. Voiceover narration added via WAN 2.5.",
    videos: [],
    ref: "Corporate training use case",
    style: "Documentary",
    duration: "90 seconds",
    creator: "SafetyFirst Corp"
  },
  {
    id: 25,
    title: "Music Visualizer — EDM Set",
    location: "Ibiza, Spain",
    lat: 38.9067, lng: 1.4206,
    date: "2026-03-29",
    source: "community", status: "pending",
    description: "A psychedelic music visualizer generated with WAN 2.5, synced to an EDM track. Abstract geometric patterns morph and pulse with the beat. Created as a VJ loop for a club night.",
    videos: [],
    ref: "Music event visuals",
    style: "Experimental / Art",
    duration: "10 seconds",
    creator: "BeatVisual"
  },
  {
    id: 26,
    title: "Children's Story — The Magic Forest",
    location: "Toronto, Canada",
    lat: 43.6532, lng: -79.3832,
    date: "2026-03-17",
    source: "wan", status: "featured",
    description: "An animated children's story about a fox exploring a magical forest. WAN 2.5 generated character narration in a warm, friendly voice plus forest ambience. Colorful illustration style with gentle camera pans.",
    videos: [],
    ref: "Children's content creation",
    style: "Animation",
    duration: "10 seconds",
    creator: "StoryTime AI"
  },
  {
    id: 27,
    title: "Fitness Ad — Home Workout App",
    location: "Melbourne, Australia",
    lat: -37.8136, lng: 144.9631,
    date: "2026-03-23",
    source: "kling", status: "featured",
    description: "A high-energy fitness app commercial showing an AI trainer performing various exercises. Kling 3.0 handled complex body movements with impressive accuracy. Dynamic camera angles and motivational energy.",
    videos: [],
    ref: "Health & fitness marketing",
    style: "Commercial / Ad",
    duration: "12 seconds",
    creator: "FitTech Studios"
  },
  {
    id: 28,
    title: "Horror Short — The Hallway",
    location: "Prague, Czech Republic",
    lat: 50.0755, lng: 14.4378,
    date: "2026-03-13",
    source: "cinema", status: "featured",
    description: "A tense horror short film featuring a character walking down an endless dimly-lit hallway. Cinema Studio 2.5 created consistent atmosphere across 8 shots. Creaking floorboard audio and whispers generated with WAN 2.5.",
    videos: [],
    ref: "Horror genre showcase",
    style: "Cinematic / Film",
    duration: "40 seconds",
    creator: "DarkFrame Films"
  },
  {
    id: 29,
    title: "Sneaker Launch — Limited Edition Drop",
    location: "Portland, OR, USA",
    lat: 45.5051, lng: -122.6750,
    date: "2026-03-31",
    source: "kling", status: "pending",
    description: "A sneaker reveal video with dramatic lighting and 360-degree rotation. Kling 3.0's motion control allowed precise turntable-style product rotation. Macro details of stitching and sole texture.",
    videos: [],
    ref: "Sneaker brand marketing concept",
    style: "Commercial / Ad",
    duration: "10 seconds",
    creator: "KicksCreative"
  },
  {
    id: 30,
    title: "Travel Vlog — AI Backpacker in Patagonia",
    location: "El Calafate, Argentina",
    lat: -50.3400, lng: -72.2648,
    date: "2026-03-26",
    source: "wan", status: "featured",
    description: "An AI-generated travel vlog of a backpacker exploring Patagonian glaciers. WAN 2.5 generated wind sounds, crunching snow footsteps, and a first-person narrator describing the scenery. Stunning mountain panoramas.",
    videos: [],
    ref: "Travel vlog concept",
    style: "Documentary",
    duration: "10 seconds",
    creator: "WanderAI"
  }
];
